car_detection:
  data: 
  model_url: https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet1k_s/classification/2
  labels_file_path: data/ImageNetLabels.txt
  base_model_path: artifacts/car_detection/models/base_model

data:
  source_url: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
  download_path: artifacts/data/original_data/cifar_10


model:
  model_url: https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet21k_xl/feature_vector/2
  base_model_path: artifacts/models/base_model
  built_model_path: artifacts/models/built_model
  trained_model_path: artifacts/models/trained_model
  evaluation_score_json_path: artifacts/models/evaluation_score/scores.json
  mlflow_uri: https://dagshub.com/fhashmi10/ML_Generic.mlflow


callback: 
  callback_path: artifacts/callbacks
  tensorboard_log_path: artifacts/callbacks/tensorboard_logs
  model_checkpoint_path: artifacts/callbacks/checkpoints/model.h5


test:
  test_data_path: # path for web testing once model is ready
  test_sample_size: 1 # number of samples to pick from each class